from functools import reduce
import logging.config
import xml.etree.ElementTree as ET

from decouple import config as cfg

from modules import get_tags_and_ansid, get_tags_with_acc_answ, split_and_count_tags

# Load logging configurations
logging.config.fileConfig(cfg('FILE_PATH'))
# Instansiate logger class
logger = logging.getLogger('Grupo_Datos_C')


def chunkify(data, chunk_size=1000):
    """
    Returns a generator with the information necesary to iterate and process data

            Parameters:
                    data (xml.etree.ElementTree.Element): contains data read from xml file
                    chunk_size (int): number of data to process for each chunk
            Returns:
                    generator: contains part of that to process based on the selected chunk_size
    """
    data_lenght = len(data)

    for i in range(0, data_lenght, chunk_size):
        yield data.findall('row')[i: i + chunk_size]


def mapped_chunks(chunks):
    """
    Returns a map object with the dictionaries with the count of tags with accepted answer for each chunk
            Parameter chunks(generator):
                    chunk of data to process
            Returns:
                    mapped (list): contains Counter dictionaries objects with tags with accepted answer for each chunk
    """
    mapped = map(get_tags_and_ansid, chunks)
    mapped = map(get_tags_with_acc_answ, mapped)
    mapped = map(split_and_count_tags, mapped)
    return mapped


def reducer(list_of_dict_1, list_of_dict_2):
    """
    Returns the sum of all lists of Counter dictionaries to get total of each tag with an accepted answer per chunk

            Parametes:
                    list_of_dict_1 (list): list of Counter objects generated per chunk
                    list_of_dict_2 (list): list of Counter objects generated per chunk
            Returns:
                    Counter Object with sum of tags with accepted id per chunk
    """
    return list_of_dict_1 + list_of_dict_2


def get_top_10(dictrionary):
    """
    Returns the top 10 tags with accepted answers as a list of tuples
        Parameter:
                dictrionary (Counter object): contains final count of all tags with accepted answer id
        Returns:
                sorted list with top 10 tags with accepted answer id in descending order
    """
    return sorted(dictrionary.items(), key=lambda item: item[1], reverse=True)[:10]


def top_10_tags():
    # Read xml file and load data to root
    file_xml = ET.parse('posts.xml')
    root = file_xml.getroot()

    # Load data by chunks of 1000 data each
    data_chunks = chunkify(root, 1000)
    # Perform first step of map reduce
    mapped_chunk = mapped_chunks(data_chunks)
    # Perform sum of all Counter objects generated by mapped_chunks function
    reduced = reduce(reducer, mapped_chunk)
    # Get top 10 tags with accepted answer id and display
    top_10 = get_top_10(reduced)
    logger.info("Top 10 tags with accepted answer id: ")
    for tag, count in top_10:
        logger.info(f'\t Tag: {tag}, Count: {count}')


# Run main script
if __name__ == '__main__':
    # Get top 10 tags with accepted answer id
    top_10_tags()
